# Overrides específicos para desenvolvimento local

services:
  db:
    environment:
      POSTGRES_DB: aptos_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev123
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  backend:
    build:
      target: development
    environment:
      DJANGO_SETTINGS_MODULE: app.conf.development
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "*"
      POSTGRES_DB: aptos_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev123
    volumes:
      - ./:/app
      - media_volume:/app/media
      - static_volume:/app/static
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: /api/v1
      VITE_BACKEND_PROXY_TARGET: http://backend:8000
    networks:
      - aptos-network
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_dev_data:
