version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: aptos
      POSTGRES_USER: aptos_user
      POSTGRES_PASSWORD: changeme123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aptos_user -d aptos"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings_docker
      - POSTGRES_DB=aptos
      - POSTGRES_USER=aptos_user
      - POSTGRES_PASSWORD=changeme123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/api/v1/health/ >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8001/api/v1
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3001:3000"
