# Generated by Django 5.2 on 2025-04-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='city',
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='country',
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='state',
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='street',
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='aptos',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptos_building_name', to='aptos.builders'),
        ),
    ]
