# Generated by Django 5.2 on 2025-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0002_builders_remove_aptos_city_remove_aptos_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptos',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='aptos/aptos_photos'),
        ),
        migrations.AddField(
            model_name='aptos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='aptos/aptos_videos'),
        ),
    ]
