# Generated by Django 5.2 on 2025-04-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0003_aptos_photos_aptos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptos',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='aptos',
            name='video',
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='aptos/aptos_photos')),
                ('video', models.FileField(blank=True, null=True, upload_to='aptos/aptos_videos')),
                ('apto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='aptos.aptos')),
            ],
        ),
    ]
