# Generated by Django 5.2 on 2025-04-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0004_remove_aptos_photos_remove_aptos_video_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='video',
        ),
        migrations.AddField(
            model_name='aptos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='aptos/aptos_videos'),
        ),
    ]
