# Generated by Django 5.2 on 2025-04-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0005_remove_foto_video_aptos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
