# Generated by Django 5.2 on 2025-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0006_foto_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='description',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
