# Generated by Django 4.2.11 on 2025-04-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0007_alter_foto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='builders',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='builders/builders_videos'),
        ),
        migrations.CreateModel(
            name='BuilderFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=10, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='builders/builders_photos')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builder_fotos', to='aptos.builders')),
            ],
        ),
    ]
