# Generated by Django 5.2 on 2025-09-28 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0008_builders_video_builderfoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('INADIMPLENTE', 'Inadimplente'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('renda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, null=True)),
                ('responsavel_legal', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco_completo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=15)),
                ('status_novo', models.CharField(max_length=15)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='aptos.inquilino')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoInquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RG', 'RG'), ('CNH', 'CNH'), ('COMP_RENDA', 'Comprovante de Renda'), ('COMP_RESIDENCIA', 'Comprovante de Residência'), ('OUTROS', 'Outros')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('arquivo', models.FileField(upload_to='inquilinos/documentos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='aptos.inquilino')),
            ],
            options={
                'verbose_name': 'Documento do Inquilino',
                'verbose_name_plural': 'Documentos dos Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='InquilinoApartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptos.aptos')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptos.inquilino')),
            ],
            options={
                'verbose_name': 'Associação Inquilino-Apartamento',
                'verbose_name_plural': 'Associações Inquilino-Apartamento',
                'unique_together': {('inquilino', 'apartamento', 'data_inicio')},
            },
        ),
        migrations.AddField(
            model_name='inquilino',
            name='apartamentos',
            field=models.ManyToManyField(related_name='inquilinos', through='aptos.InquilinoApartamento', to='aptos.aptos'),
        ),
    ]
