# Generated by Django 5.2 on 2025-09-28 12:57

import aptos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0009_inquilino_historicostatus_documentoinquilino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True, validators=[aptos.validators.validar_cnpj_django]),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[aptos.validators.validar_cpf_django]),
        ),
    ]
