# Generated by Django 5.2 on 2025-09-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0010_alter_inquilino_cnpj_alter_inquilino_cpf'),
    ]

    operations = [
    ]
