# Generated by Django 5.2 on 2025-09-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0011_auto_20250928_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoinquilino',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Documento do Inquilino', 'verbose_name_plural': 'Documentos dos Inquilinos'},
        ),
        migrations.AddField(
            model_name='documentoinquilino',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentoinquilino',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentoinquilino',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentoinquilino',
            name='tamanho',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoinquilino',
            name='tipo_documento',
            field=models.CharField(choices=[('RG', 'RG'), ('CNH', 'CNH'), ('COMPROVANTE_RENDA', 'Comprovante de Renda'), ('COMPROVANTE_RESIDENCIA', 'Comprovante de Residência'), ('OUTROS', 'Outros')], default='OUTROS', max_length=30),
        ),
        migrations.AddField(
            model_name='documentoinquilino',
            name='versao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='documentoinquilino',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='documentoinquilino',
            name='tipo',
        ),
        migrations.AlterUniqueTogether(
            name='documentoinquilino',
            unique_together={('inquilino', 'tipo_documento', 'versao')},
        ),
    ]
