# Generated by Django 5.2 on 2025-09-28 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0012_alter_documentoinquilino_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('criterio', models.CharField(choices=[('DIAS_SEM_PAGAMENTO', 'Dias sem Pagamento'), ('TEMPO_INATIVO', 'Tempo Inativo'), ('VIOLACAO_CONTRATO', 'Violação de Contrato'), ('TERMINO_ASSOCIACAO', 'Término de Associação')], max_length=30)),
                ('parametros', models.JSONField(default=dict)),
                ('acao', models.CharField(choices=[('INADIMPLENTE', 'Marcar como Inadimplente'), ('BLOQUEADO', 'Bloquear Inquilino'), ('INATIVO', 'Marcar como Inativo'), ('NOTIFICAR', 'Apenas Notificar')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('automatica', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Status',
                'verbose_name_plural': 'Regras de Status',
            },
        ),
        migrations.CreateModel(
            name='StatusInquilino',
            fields=[
            ],
            options={
                'verbose_name': 'Status de Inquilino',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('aptos.inquilino',),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='categoria_motivo',
            field=models.CharField(choices=[('MANUAL', 'Alteração Manual'), ('AUTOMATICO', 'Alteração Automática'), ('INADIMPLENCIA', 'Inadimplência Detectada'), ('PAGAMENTO', 'Pagamento Recebido'), ('VIOLACAO_CONTRATO', 'Violação de Contrato'), ('TERMINO_LOCACAO', 'Término de Locação'), ('REATIVACAO', 'Reativação')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicostatus',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='motivo',
            field=models.TextField(default='Alteração de status'),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_anterior',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('INADIMPLENTE', 'Inadimplente'), ('BLOQUEADO', 'Bloqueado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='historicostatus',
            name='status_novo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('INADIMPLENTE', 'Inadimplente'), ('BLOQUEADO', 'Bloqueado')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='historicostatus',
            index=models.Index(fields=['inquilino', 'timestamp'], name='aptos_histo_inquili_39d956_idx'),
        ),
        migrations.AddIndex(
            model_name='historicostatus',
            index=models.Index(fields=['status_novo', 'timestamp'], name='aptos_histo_status__ccd1b0_idx'),
        ),
    ]
