# Generated by Django 5.2 on 2025-09-28 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0013_regrastatus_statusinquilino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquilinoapartamento',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Associação Inquilino-Apartamento', 'verbose_name_plural': 'Associações Inquilino-Apartamento'},
        ),
        migrations.AddField(
            model_name='inquilinoapartamento',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquilinoapartamento',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associacoes_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquilinoapartamento',
            name='valor_aluguel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inquilinoapartamento',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes_inquilino', to='aptos.aptos'),
        ),
        migrations.AlterField(
            model_name='inquilinoapartamento',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes_apartamento', to='aptos.inquilino'),
        ),
        migrations.CreateModel(
            name='HistoricoAssociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADA', 'Criada'), ('ATUALIZADA', 'Atualizada'), ('FINALIZADA', 'Finalizada'), ('REATIVADA', 'Reativada')], max_length=20)),
                ('detalhes', models.JSONField(default=dict)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='aptos.inquilinoapartamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Associação',
                'verbose_name_plural': 'Históricos de Associações',
                'ordering': ['-timestamp'],
            },
        ),
    ]
