# Generated by Django 5.2 on 2025-10-01 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0016_merge_20250928_2100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaOcupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(unique=True)),
                ('total_apartamentos', models.IntegerField()),
                ('apartamentos_ocupados', models.IntegerField()),
                ('taxa_ocupacao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pf_ocupados', models.IntegerField(default=0)),
                ('pj_ocupados', models.IntegerField(default=0)),
                ('tempo_medio_locacao_dias', models.IntegerField(blank=True, null=True)),
                ('valor_medio_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica de Ocupação',
                'verbose_name_plural': 'Métricas de Ocupação',
                'ordering': ['-data_referencia'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('INQUILINOS_ATIVOS', 'Inquilinos Ativos'), ('OCUPACAO', 'Taxa de Ocupação'), ('INADIMPLENTES', 'Inadimplentes'), ('ROTATIVIDADE', 'Rotatividade'), ('HISTORICO_LOCACOES', 'Histórico de Locações')], max_length=30)),
                ('descricao', models.TextField()),
                ('query_sql', models.TextField(blank=True, null=True)),
                ('parametros_padrao', models.JSONField(default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Relatório',
                'verbose_name_plural': 'Templates de Relatórios',
            },
        ),
        migrations.CreateModel(
            name='RelatorioExecucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametros', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('total_registros', models.IntegerField(blank=True, null=True)),
                ('arquivo_gerado', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('formato', models.CharField(default='PDF', max_length=10)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('erro_detalhes', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='aptos.relatoriotemplate')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
