# Generated by Django 5.2 on 2025-10-04 17:11

import aptos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptos', '0018_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=30)),
                ('profissao', models.CharField(max_length=100)),
                ('cpf', models.CharField(help_text='Formato: XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[aptos.validators.validar_cpf_django])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_rua', models.CharField(max_length=200)),
                ('endereco_numero', models.CharField(max_length=20)),
                ('endereco_bairro', models.CharField(max_length=100)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_estado', models.CharField(max_length=2)),
                ('endereco_cep', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
