name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aptos
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare temp upload directory
        run: |
          mkdir -p "$RUNNER_TEMP/uploads"
          mkdir -p "$RUNNER_TEMP/media"
      - name: Run Django tests with coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_aptos
          DATABASE_SSL_REQUIRE: "false"
          DJANGO_DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
          DJANGO_MEDIA_ROOT: ${{ runner.temp }}/media
          DJANGO_FILE_UPLOAD_TEMP_DIR: ${{ runner.temp }}/uploads
        run: |
          pytest --cov=aptos --cov-report=xml --cov-report=term-missing --cov-fail-under=85
      - uses: codecov/codecov-action@v3

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install and test
        run: |
          cd frontend
          npm install
          npm run test:coverage
      - uses: codecov/codecov-action@v3
        with:
          directory: frontend/coverage

  # e2e-tests removed per project decision (flaky in CI environment)
